/**
 * Gate 2 Core Interactive Teaching Board.
 * The board owns educational objects; rendering remains replaceable by adapters.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { Clipboard, Copy, Eraser, Eye, EyeOff, FilePlus2, Group, Hand, Lock, Maximize2, MousePointer2, Pencil, Play, Redo2, Save, Square, Trash2, Undo2, Ungroup, ZoomIn, ZoomOut } from "lucide-react";
import { BoardDocument, BoardPage, CoreObject, CoreObjectType, Stroke, cloneDocument, createDocument, createObject, createPage, getActivePage, persistDocument, restoreDocument } from "@/lib/coreBoard";

type Tool = "select" | "pen" | "highlighter" | "eraser" | "shape";
type HistoryItem = { document: BoardDocument; selectedId: string; tool: Tool };
const mixedText = "العربية + English + 123 + x² + symbols";

export default function CoreBoardBench() {
  const [document, setDocument] = useState<BoardDocument>(() => createDocument());
  const [selectedId, setSelectedId] = useState("");
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [clipboard, setClipboard] = useState<CoreObject[]>([]);
  const [tool, setTool] = useState<Tool>("select");
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [future, setFuture] = useState<HistoryItem[]>([]);
  const [presentation, setPresentation] = useState(false);
  const [notice, setNotice] = useState("لوحة جديدة جاهزة");
  const [zoom, setZoom] = useState(1);
  const [drawing, setDrawing] = useState<Stroke | null>(null);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const stageRef = useRef<HTMLDivElement>(null);
  const boardRef = useRef<HTMLElement>(null);

  const page = getActivePage(document);
  const selected = page?.objects.find((item) => item.id === selectedId);
  const snapshot = useMemo(() => ({ document, selectedId, tool }), [document, selectedId, tool]);

  useEffect(() => { const restored = restoreDocument(); if (restored) { setDocument(restored); setNotice("تمت استعادة آخر لوحة محلية"); } }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if ((event.target as HTMLElement)?.tagName === "INPUT") return;
      const mod = event.metaKey || event.ctrlKey;
      if (mod && event.key.toLowerCase() === "c") { event.preventDefault(); copySelected(); }
      if (mod && event.key.toLowerCase() === "v") { event.preventDefault(); pasteSelected(); }
      if (mod && event.key.toLowerCase() === "z") { event.preventDefault(); event.shiftKey ? redo() : undo(); }
      if (mod && event.key.toLowerCase() === "y") { event.preventDefault(); redo(); }
      if (event.key === "Delete" || event.key === "Backspace") { event.preventDefault(); remove(); }
      if (event.key === "ArrowLeft") move(-12, 0);
      if (event.key === "ArrowRight") move(12, 0);
      if (event.key === "ArrowUp") move(0, -12);
      if (event.key === "ArrowDown") move(0, 12);
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  });

  function commit(next: BoardDocument, message: string, nextSelected = selectedId) {
    setHistory((current) => [...current.slice(-24), { document: cloneDocument(document), selectedId, tool }]);
    setFuture([]); setDocument(next); setSelectedId(nextSelected); setNotice(message);
  }
  function updatePage(updater: (page: BoardPage) => BoardPage, message: string) { commit({ ...document, pages: document.pages.map((item) => item.id === page.id ? updater(item) : item), updatedAt: new Date().toISOString() }, message); }
  function addObject(type: CoreObjectType, content: string) { const item = createObject(type, content, 54 + (page.objects.length % 3) * 190, 52 + Math.floor(page.objects.length / 3) * 100); updatePage((current) => ({ ...current, objects: [...current.objects, item] }), `${type} أضيف إلى اللوحة`); setSelectedId(item.id); }
  function duplicate() { if (!selected) return; const item = { ...selected, id: `${selected.type.toLowerCase()}_${Date.now()}`, position: { x: selected.position.x + 24, y: selected.position.y + 24 }, metadata: { ...selected.metadata, version: selected.metadata.version + 1 } }; updatePage((current) => ({ ...current, objects: [...current.objects, item] }), "تم تكرار الكائن"); setSelectedId(item.id); }
  function remove() { if (!selected) return; updatePage((current) => ({ ...current, objects: current.objects.filter((item) => item.id !== selected.id) }), "تم حذف الكائن"); setSelectedId(""); setSelectedIds([]); }
  function copySelected() { const chosen = page.objects.filter((item) => selectedIds.includes(item.id) || item.id === selectedId); if (!chosen.length) return setNotice("اختر كائنًا لنسخه"); setClipboard(cloneDocument({ ...document, pages: [{ ...page, objects: chosen }] }).pages[0].objects); setNotice(`تم نسخ ${chosen.length} كائن`); }
  function pasteSelected() { if (!clipboard.length) return setNotice("الحافظة فارغة"); const pasted = clipboard.map((item) => ({ ...item, id: `${item.type.toLowerCase()}_${Date.now()}_${Math.random().toString(36).slice(2, 5)}`, position: { x: item.position.x + 28, y: item.position.y + 28 } })); updatePage((current) => ({ ...current, objects: [...current.objects, ...pasted] }), "تم لصق الكائنات"); setSelectedId(pasted[0].id); setSelectedIds(pasted.map((item) => item.id)); }
  function groupSelected() { const chosen = page.objects.filter((item) => selectedIds.includes(item.id) || item.id === selectedId); if (chosen.length < 2) return setNotice("اختر كائنين أو أكثر للتجميع"); const group = createObject("GroupObject", `${chosen.length} objects`, Math.min(...chosen.map((item) => item.position.x)), Math.min(...chosen.map((item) => item.position.y))); group.size = { width: Math.max(...chosen.map((item) => item.position.x + item.size.width)) - group.position.x, height: Math.max(...chosen.map((item) => item.position.y + item.size.height)) - group.position.y }; group.metadata.label = "Group container"; updatePage((current) => ({ ...current, objects: [...current.objects.filter((item) => !chosen.some((selectedItem) => selectedItem.id === item.id)), group] }), "تم تجميع الكائنات"); setSelectedId(group.id); setSelectedIds([group.id]); }
  function ungroupSelected() { if (!selected || selected.type !== "GroupObject") return setNotice("اختر حاوية Group لفكها"); setNotice("Group container جاهز لفك المحتوى بعد ربط children في نموذج المجال"); }
  function clearBoard() { updatePage((current) => ({ ...current, objects: [] }), "أصبحت اللوحة فارغة"); setSelectedId(""); setSelectedIds([]); }
  function fitContent() { if (!page.objects.length) return setNotice("لا توجد كائنات للملاءمة"); setZoom(.82); setPan({ x: 0, y: 0 }); setNotice("تمت ملاءمة المحتوى داخل إطار اللوحة"); }
  function handleWheel(event: React.WheelEvent) { event.preventDefault(); if (event.ctrlKey || event.metaKey) { setZoom((value) => Math.max(.7, Math.min(1.5, value - event.deltaY * .001))); } else { setPan((value) => ({ x: value.x - event.deltaX, y: value.y - event.deltaY })); } }
  function requestFullscreen() { boardRef.current?.requestFullscreen?.().then(() => setNotice("وضع ملء الشاشة مفعّل")).catch(() => setNotice("تعذر تفعيل ملء الشاشة")); }
  function patchSelected(patch: Partial<CoreObject>, message: string) { if (!selected || selected.metadata.locked) return setNotice(selected ? "الكائن مقفل" : "اختر كائنًا أولًا"); updatePage((current) => ({ ...current, objects: current.objects.map((item) => item.id === selected.id ? { ...item, ...patch } : item) }), message); }
  function move(dx: number, dy: number) { if (!selected) return; patchSelected({ position: { x: Math.max(8, selected.position.x + dx), y: Math.max(8, selected.position.y + dy) } }, "تم تحريك الكائن"); }
  function toggleLock() { if (!selected) return; patchSelected({ metadata: { ...selected.metadata, locked: !selected.metadata.locked } }, selected.metadata.locked ? "تم فتح قفل الكائن" : "تم قفل الكائن"); }
  function toggleVisible() { if (!selected) return; patchSelected({ metadata: { ...selected.metadata, visible: !selected.metadata.visible } }, selected.metadata.visible ? "تم إخفاء الكائن" : "تم إظهار الكائن"); }
  function save() { persistDocument(document); setNotice("حُفظت الصفحات والكائنات والمواضع محليًا"); }
  function undo() { const previous = history.at(-1); if (!previous) return setNotice("لا توجد عملية للتراجع"); setFuture((current) => [{ document: cloneDocument(document), selectedId, tool }, ...current]); setHistory((current) => current.slice(0, -1)); setDocument(previous.document); setSelectedId(previous.selectedId); setTool(previous.tool); setNotice("تراجع على مستوى العملية"); }
  function redo() { const next = future[0]; if (!next) return setNotice("لا توجد عملية للإعادة"); setHistory((current) => [...current, { document: cloneDocument(document), selectedId, tool }]); setFuture((current) => current.slice(1)); setDocument(next.document); setSelectedId(next.selectedId); setTool(next.tool); setNotice("إعادة على مستوى العملية"); }
  function addPage() { const next = createPage(`Page ${document.pages.length + 1}`, []); commit({ ...document, pages: [...document.pages, next], activePageId: next.id }, "تم إنشاء صفحة جديدة", ""); }
  function duplicatePage() { const next = createPage(`${page.name} copy`, page.objects.map((item) => ({ ...item, id: `${item.id}_copy_${Date.now()}` }))); commit({ ...document, pages: [...document.pages, next], activePageId: next.id }, "تم تكرار الصفحة", ""); }
  function deletePage() { if (document.pages.length === 1) return setNotice("لا يمكن حذف الصفحة الوحيدة"); const index = document.pages.findIndex((item) => item.id === page.id); const pages = document.pages.filter((item) => item.id !== page.id); commit({ ...document, pages, activePageId: pages[Math.max(0, index - 1)].id }, "تم حذف الصفحة", ""); }
  function selectPage(id: string) { setDocument((current) => ({ ...current, activePageId: id })); setSelectedId(""); setSelectedIds([]); }
  function renamePage() { const name = window.prompt("اسم الصفحة", page.name); if (name?.trim()) { updatePage((current) => ({ ...current, name: name.trim() }), "تمت إعادة تسمية الصفحة"); } }
  function reorderPage(direction: -1 | 1) { const index = document.pages.findIndex((item) => item.id === page.id); const target = index + direction; if (target < 0 || target >= document.pages.length) return; const pages = [...document.pages]; [pages[index], pages[target]] = [pages[target], pages[index]]; commit({ ...document, pages }, "تم تغيير ترتيب الصفحات", selectedId); }
  function handleObjectSelect(event: React.PointerEvent, id: string) { event.stopPropagation(); const multi = event.metaKey || event.ctrlKey; if (multi) { const next = selectedIds.includes(id) ? selectedIds.filter((item) => item !== id) : [...selectedIds, id]; setSelectedIds(next); setSelectedId(next.at(-1) ?? ""); } else { setSelectedId(id); setSelectedIds([id]); } }
  function pointerPosition(event: React.PointerEvent) { const rect = stageRef.current?.getBoundingClientRect(); return rect ? { x: (event.clientX - rect.left) / zoom, y: (event.clientY - rect.top) / zoom } : { x: 0, y: 0 }; }
  function startDraw(event: React.PointerEvent) { if (tool === "select" || presentation) return; const point = pointerPosition(event); setDrawing({ points: [point], color: tool === "highlighter" ? "#d56b58" : "#314d3e", width: tool === "highlighter" ? 12 : 3, tool: tool === "eraser" ? "eraser" : tool === "highlighter" ? "highlighter" : "pen" }); event.currentTarget.setPointerCapture?.(event.pointerId); }
  function continueDraw(event: React.PointerEvent) { if (!drawing) return; setDrawing({ ...drawing, points: [...drawing.points, pointerPosition(event)] }); }
  function finishDraw() { if (!drawing) return; const object = createObject("DrawingObject", "stroke", drawing.points[0]?.x ?? 30, drawing.points[0]?.y ?? 30); object.size = { width: 260, height: 120 }; object.stroke = drawing; const next = { ...document, pages: document.pages.map((item) => item.id === page.id ? { ...item, objects: [...item.objects, object] } : item) }; setDrawing(null); commit(next, "تم حفظ الرسم المتجهي ككائن قابل للاستعادة", object.id); }
  function pathFor(stroke?: Stroke) { return stroke?.points.map((point, index) => `${index ? "L" : "M"} ${point.x} ${point.y}`).join(" ") ?? ""; }

  return <section ref={boardRef} className={`core-board ${presentation ? "is-presenting" : ""}`} dir="rtl">
    <div className="core-board-header"><div><span className="kicker">GATE 2 / CORE INTERACTIVE TEACHING BOARD</span><h2>نواة مساحة التعليم التفاعلية</h2><p>لوحة عامة · كائنات قابلة لإعادة الاستخدام · محلية أولًا</p></div><span className="core-notice">{notice}</span></div>
    {!presentation && <div className="core-toolbar"><div className="tool-group"><button className={tool === "select" ? "tool active" : "tool"} onClick={() => setTool("select")} aria-label="تحديد"><MousePointer2 size={15} /></button><button className={tool === "pen" ? "tool active" : "tool"} onClick={() => setTool("pen")} aria-label="قلم"><Pencil size={15} /></button><button className={tool === "highlighter" ? "tool active" : "tool"} onClick={() => setTool("highlighter")} aria-label="تمييز"><Pencil size={15} /></button><button className={tool === "eraser" ? "tool active" : "tool"} onClick={() => setTool("eraser")} aria-label="ممحاة"><Eraser size={15} /></button><button className={tool === "shape" ? "tool active" : "tool"} onClick={() => setTool("shape")} aria-label="شكل"><Square size={15} /></button></div><div className="tool-group"><button onClick={() => addObject("TextObject", mixedText)}>+ نص مختلط</button><button onClick={() => addObject("ShapeObject", "شكل")}>+ شكل</button><button onClick={() => addObject("ImageObject", "صورة تعليمية")}>+ صورة</button><button onClick={() => addObject("SentenceObject", "قرأَ الطالبُ الكتابَ")}>+ Sentence</button><button onClick={() => addObject("EquationObject", "2x + 5 = 15")}>+ Equation</button></div><div className="tool-group tool-end"><button onClick={undo} aria-label="تراجع"><Undo2 size={15} /></button><button onClick={redo} aria-label="إعادة"><Redo2 size={15} /></button><button onClick={copySelected} aria-label="نسخ"><Copy size={15} /></button><button onClick={pasteSelected} aria-label="لصق"><Clipboard size={15} /></button><button onClick={groupSelected} aria-label="تجميع"><Group size={15} /></button><button onClick={ungroupSelected} aria-label="فك التجميع"><Ungroup size={15} /></button><button onClick={() => setZoom((value) => Math.min(1.5, value + .1))} aria-label="تكبير"><ZoomIn size={15} /></button><button onClick={() => setZoom((value) => Math.max(.7, value - .1))} aria-label="تصغير"><ZoomOut size={15} /></button><button onClick={fitContent}>ملاءمة</button><button onClick={clearBoard}>فارغة</button><button onClick={requestFullscreen}><Maximize2 size={15} /></button><button onClick={save}><Save size={15} /> حفظ</button><button onClick={() => { setPresentation(true); setNotice("وضع العرض مفعّل"); }}><Play size={15} /> عرض</button></div></div>}
    {presentation && <div className="presentation-banner"><span>Presentation Mode · الصفحات والكائنات جاهزة للشرح</span><button onClick={() => { setPresentation(false); setNotice("عادت أدوات التحرير"); }}>تحرير</button></div>}
    <div className="core-layout"><aside className="pages-panel"><div className="panel-title"><span>الصفحات</span><button onClick={addPage} aria-label="صفحة جديدة"><FilePlus2 size={15} /></button></div>{document.pages.map((item, index) => <button className={item.id === page.id ? "page-item active" : "page-item"} key={item.id} onClick={() => selectPage(item.id)}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item.name}</strong><small>{item.objects.length} كائنات</small></button>)}<div className="page-actions"><button onClick={duplicatePage}>تكرار</button><button onClick={renamePage}>تسمية</button><button onClick={deletePage}>حذف</button></div><div className="page-actions"><button onClick={() => reorderPage(-1)}>↑</button><button onClick={() => reorderPage(1)}>↓</button></div><div className="panel-caption">Local-first persistence<br />Page viewport ready</div></aside>
      <div className="core-stage-wrap"><div className="stage-meta"><span>{page.name} · {document.title}</span><span>{Math.round(zoom * 100)}% · {page.objects.length} objects</span></div><div ref={stageRef} className="core-stage" style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`, transformOrigin: "top right" }} onPointerDown={startDraw} onPointerMove={continueDraw} onPointerUp={finishDraw} onWheel={handleWheel} aria-label="سطح السبورة التعليمية"><div className="core-grid" />{page.objects.map((item) => item.metadata.visible && <button key={item.id} className={`core-object ${item.id === selectedId ? "selected" : ""} ${item.metadata.locked ? "locked" : ""}`} style={{ right: item.position.x, top: item.position.y, width: item.size.width, height: item.size.height, transform: `rotate(${item.rotation}deg)`, color: item.style.color, background: item.style.background }} onPointerDown={(event) => handleObjectSelect(event, item.id)} aria-label={`${item.type}: ${item.content}`}><span className="core-object-type">{item.type}</span><strong>{item.type === "DrawingObject" && item.stroke ? <svg viewBox="0 0 280 130" className="stroke-preview"><path d={pathFor(item.stroke)} fill="none" stroke={item.stroke.color} strokeWidth={item.stroke.width} strokeLinecap="round" /></svg> : item.type === "ShapeObject" ? <Square size={28} /> : item.type === "ImageObject" ? <span className="image-placeholder"><Eye size={18} /> {item.content}</span> : item.content}</strong><small>{item.metadata.locked ? "مقفل" : item.metadata.label}</small><i><Maximize2 size={12} /></i></button>)}{drawing && <svg className="drawing-overlay"><path d={pathFor(drawing)} fill="none" stroke={drawing.color} strokeWidth={drawing.width} strokeLinecap="round" opacity={drawing.tool === "highlighter" ? .38 : 1} /></svg>}</div><div className="stage-footer"><span>pan-safe surface · pointer / touch</span><span>viewport persisted in document contract</span></div></div>
      <aside className="object-inspector"><div className="panel-title"><span>Object Inspector</span><span className="inspector-status">{selected ? selected.type : "لا تحديد"}</span></div>{selected ? <><div className="inspector-content"><label>المحتوى<input value={selected.content} onChange={(event) => patchSelected({ content: event.target.value }, "تم تحرير الكائن")} /></label><div className="inspector-grid"><button onClick={() => move(-12, 0)}>← تحريك</button><button onClick={() => move(12, 0)}>تحريك →</button><button onClick={() => patchSelected({ size: { ...selected.size, width: selected.size.width + 24, height: selected.size.height + 8 } }, "تم تغيير الحجم")}>تغيير الحجم</button><button onClick={() => patchSelected({ rotation: selected.rotation + 15 }, "تم تدوير الكائن")}>تدوير 15°</button></div><div className="inspector-grid"><button onClick={duplicate}><Copy size={13} /> تكرار</button><button onClick={toggleLock}><Lock size={13} /> {selected.metadata.locked ? "فتح" : "قفل"}</button><button onClick={toggleVisible}>{selected.metadata.visible ? <EyeOff size={13} /> : <Eye size={13} />} إظهار</button><button onClick={remove}><Trash2 size={13} /> حذف</button></div></div><div className="inspector-foot">version {selected.metadata.version} · serialization ready<br />source: {selected.metadata.source}</div></> : <div className="empty-inspector">اختر كائنًا لرؤية خصائصه وتطبيق دورة Edit → Transform → Save → Restore.</div>}</aside>
    </div><div className="core-board-footer"><span><Hand size={14} /> لا يعتمد على hover فقط</span><span>Core Board ↔ Educational Object ↔ Domain Toolkit</span><span>Gate 2 · working branch</span></div>
  </section>;
}
